services:
  api:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
  database:
    container_name: mysql-db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=badminton
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=p@ssw0rd
    ports:
      - "3306:3306"